; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
lib_deps =
  fastled/FastLED @ ^3.10.3
  vshymanskyy/Preferences @ ^2.2.2
build_flags = 
  -D __BASE_NAME__=\"8266-node:\"
  -D __LOGGER_BAUDRATE__=115200
; [env:esp32-c3-devkitm-1]
; platform = espressif32@6.6.0
; board = esp32-c3-devkitm-1
; framework = arduino
; lib_deps = 
;   fastled/FastLED @ ^3.10.3
; monitor_speed = 460800
; monitor_filters = esp32_exception_decoder

; board_build.f_flash = 40000000L
; board_build.flash_mode = dio
; build_flags = 
; 	-DARDUINO_USB_CDC_ON_BOOT=1
; 	-DARDUINO_USB_MODE=1


[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
lib_deps = 
  fastled/FastLED @ ^3.10.3
build_flags=
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_MODE=1
  -D __BASE_NAME__=\"c3-node:\"


[env:esp32doit-devkit-v1]
monitor_speed = 115200
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
lib_deps = 
  fastled/FastLED @ ^3.10.3
monitor_filters = esp32_exception_decoder
monitor_flags =--echo
build_flags=
  -D __BASE_NAME__=\"32-node:\"

